# Working with Array

<h3> Table of Contents </h3>

<div style="margin-top: 20px">
    <ul>
        <li><a href="#arrays">Arrays</a>
        <li><a href="#function">Array function and methods</a></li>
        <li><a href="#lab">Practice Assignment</a></li>
            </ul>
       
</div>

<h3> Arrays </h3>
<a id="arrays"></a>

<p> Arrays are like sequence of elements. But, the elements have to be the same type. Although arrays are well known in other programming languages (C, C++, C#, Javascript, etc.). In Python, arrays are not common, they are just lists with special characteristic in that its items have to be numeric and of the same type. Python Programmers usually refer to lists when they deal with arrays, but Python offers a library called arrays, that offers some flexibility and functionality of working with arrays. </p> 

<p> To create an array, you need to import the arrays module/library. The cell below shows an example of creating an array. </p>

In [13]:
import numpy as np #imports the array module to be able to use its functions

numbers = np.array([1,2,3,4]) #creates and array of type integer,
# then specifies the array content as (1,2,3,4)

print(numbers)
print(type(numbers)) #prints the type of variable numbers. In this case it prints Array

prices = np.array([1.2, 3.5, 4.4, 2.0]) #creates and array of type float,
# with content as (1.2,3.5,4.4, 2.0)

print(prices) # prints the array. In this case [1.2, 3.5, 4.4, 2.0]
print(type(prices))


s = np.array(['Helo', 'World' , '!']) #creates and array of type string,
print(s) # prints the string array. 
print(type(s))

[1 2 3 4]
<class 'numpy.ndarray'>
[1.2 3.5 4.4 2. ]
<class 'numpy.ndarray'>
['Helo' 'World' '!']
<class 'numpy.ndarray'>


<p> You can use indexing and slicing to access an array item or a subarray. </p>
<p> For example: </p>

In [4]:
print(numbers[3]) # prints 4
print(numbers[-2]) # prints -2
print(numbers[2:4]) # prints array([3,4])

4
3
[3 4]


<h3> Array functions and methods </h3>
<a id="function"></a>
<p> Functions and methods that applys to arrays are the same as the ones applies to lists. </p>
<p> Below are some examples. </p>

In [5]:
# len() function in arrays
print(len(numbers)) #prints 4

4


In [8]:
# add element to the array 
# Create the array
a = np.array([[1, 1], [2, 2], [3, 3]])
a

array([[1, 1],
       [2, 2],
       [3, 3]])

In [10]:
np.insert(a, 1, 5, axis=1)

array([[1, 5, 1],
       [2, 5, 2],
       [3, 5, 3]])

In [12]:
# append method
np.append([[1, 2, 3], [4, 5, 6]], [[7, 8, 9]], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

<p> From the examples, you saw that lists function, operations, and methods are the same as arrays. Then, what is the difference between the two?</p>
<p> the difference is more technical, the way arrays and lists are saves in memory. First, arrays are saved in memopry in a compact way that allows it to be used in big data analysis. You do not need to know the details of memory usage and allocation differences between lists and arrays in this course. Second, arrays allow mathematical operations on the array items at once. You will see this in more details when studying the Numpy in a later week. </p>

<p> So when should you use an array in Python </p>
<ul> 
    <li> When you need to store and analyze big amounts of numbers for analysis. Such as in machine learning. You use arrays. </li>
    <li> If you plan to do any numerical operations with your collection of items, use an array. </li>
</ul>


<h3> Practice Assignment </h3>
<a id="lab"></a>

<p> Q1) Write a program that creates an array (named numbers) of the integers 1,2,5,3,4,5. Then print the values of each item using its index. </p>

<p> Q2) Write a program that reverse the order of the items of the array numbers and print the new ordered array. </p>

<p> Q3) Write a program that prints the number of instances of (5) in the array numbers. </p>

<p> Q4) Write a program that creates the array (names) that includes the items ("Mike", "John", "Zara"). <br>
Then checks if the array has dplicate values. </p>

Hint: Use the index to compare the items. You have to print the result of 3 comparisons.